services:
  mysql:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
    ports:
      - '3306'
