spring:
  application:
    name: bookshop
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
app:
  jwt:
    secret: ${JWT_SECRET:TXlCb29rU2hvcFN1cGVyU2VjcmV0S2V5MjAyNFhZWjEyM2dpdCBjaGVja291dCBtYWluIQ==}
    expiration: ${JWT_ACCESS_EXPIRATION:86400000}
    tokenRefreshExpirationTime: ${JWT_REFRESH_EXPIRATION:604800000}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
